### ISSUE TITLE
missing openmrs-runtime.properties file

### ISSUE THREAD

**Issue by douglassllc** [fortitudoinc/fortitudoinc-ansible#5]
OS:  Ubuntu 18.04.1 LTS

Is the docker image attempting to reference the openmrs-runtime.properties from my local system?

```
Oct 31, 2018 9:33:26 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 9241 ms
+ curl -L http://localhost:8080/openmrs/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
WARN - OpenmrsUtil.getRuntimePropertiesFilePathName(2113) |2018-10-31 21:33:30,296| Unable to find a runtime properties file at /usr/local/tomcat/openmrs-runtime.properties
WARN - OpenmrsUtil.getRuntimePropertiesFilePathName(2141) |2018-10-31 21:33:30,308| Unable to find properties file: /usr/local/tomcat/.OpenMRS/openmrs-runtime.properties
100 12082    0 12082    0     0   4844      0 --:--:--  0:00:02 --:--:--  9431
+ sleep 15
WARN - InitializationFilter.verifyConnection(987) |2018-10-31 21:33:35,690| Error while checking the connection user account
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2316)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.openmrs.web.filter.initialization.InitializationFilter.verifyConnection(InitializationFilter.java:978)
	at org.openmrs.web.filter.initialization.InitializationFilter.access$300(InitializationFilter.java:84)
	at org.openmrs.web.filter.initialization.InitializationFilter$InitializationCompletion$1.run(InitializationFilter.java:1470)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Access denied for user 'root'@'172.18.0.3' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:928)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1750)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1290)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2493)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2334)
	... 16 more
+ wait 40
```

**Comment by isears** [comment]
Hi @douglassllc, thanks for using the docker infra we've put together!

This error actually doesn't look like it's related to openmrs-runtime.properties. This lookslike an issue connecting to the database. Specifically:
```
Caused by: java.sql.SQLException: Access denied for user 'root'@'172.18.0.3' (using password: YES)
```

So the openmrs docker container is using the wrong password when it tries to establish a mysql connection.

Did you specify the mysql username/password correctly in your .env file? Check your `DB_DATABASE`, `DB_USERNAME`, `DB_PASSWORD`, `MYSQL_ROOT_PASSWORD`, and `MYSQL_DATABASE` environment variables. Note that if you're using the docker container for your database, `DB_PASSWORD` must match `MYSQL_ROOT_PASSWORD`, `DB_USERNAME` must be `root`, and `DB_DATABASE` must match `MYSQL_DATABASE`.

**Comment by douglassllc** [comment]
Hi @isears,

Thank you for the quick reply.  That fixed my issue.  Now I have other questions.

1.  What is the proper way to restart.  I ran  `docker-compose -f new-db.yml up -d --build` to initially start-up everything.  I stopped everything by running `docker-compose -f new-db.yml up`.  I have no dump.sql in my backups directory, so I don't think I can run `docker-compose -f load-db.yml up -d`.  If I run `docker-compose -f new-db.yml up -d --build` again, will this recreate everything from scratch overwriting my existing data?

2.  My SSL certificate was created.  However, it took too long, so when I attempted to access the website, I received a 'Not Secure' indicator in the browser.  Is this expect on the initial run?

3.  What is the best practice for setting up this docker composition to run on system reboot?

**Comment by isears** [comment]
1. The correct way to stop the containers is `docker-compose -f new-db.yml down`. Unfortunately, the safest way to restart everything while preserving the db is to create a db dump of your database container, store that db dump in the `backups/` directory, then restart with `docker-compose -f new-db.yml down` & `docker-compose -f load-db.yml up --build`. You can either dump the db manually (using something like this: https://gist.github.com/spalladino/6d981f7b33f6e0afe6bb), or use the `util/backup.py` script in this repo. This is definitely a pain-point that needs to be fixed, I just haven't had the time to build an automation pipeline for that yet.

2. The SSL certificate won't be valid unless you set the `STAGING` environment variable to `false`. This is because the letsencrypt service will let you create unlimited staging certs, but will rate-limit you if you're creating real certs (because it's computationally expensive for them to do that). So only set the `STAGING` variable to `true` if you know you won't have to restart for a while.

3. See (1). I've been doing this all manually (back up db, stop containers, start containers). But when I get some time I'll automate this in a cron-job script or something and add that to the repo. If you have any ideas, feel free to open a PR!

**Comment by douglassllc** [comment]
@isears,

Can't thank you enough for the help.  Let me give it some thought... I will PR if something interesting comes to mind.

**Comment by isears** [comment]
No problem. I'll leave this issue open until the easy "backup & restart" feature gets implemented.

**Comment by isears** [comment]
@douglassllc This is finally fixed in my latest commit to master by using docker named volumes for the database (which we should've been doing all along). Just thought I'd ping you in case you were still interested.

**Comment by douglassllc** [comment]
@isears Thanks for the update.  I should have some time next week to check it out.  I really appreciate you keeping in the loop on your project.
